"""
Generateur de notebooks/modeling_mlflow.ipynb.

Chaque appel a cells.append() ajoute une cellule au notebook JSON.
Execution : python scripts/create_modeling_mlflow.py
"""
from pathlib import Path
import json, uuid

# Racine du projet : scripts/ -> racine/
_ROOT = Path(__file__).resolve().parent.parent


def gid():
    """Retourne un identifiant de cellule unique sur 8 caracteres."""
    return uuid.uuid4().hex[:8]


def md(s):
    """Cree une cellule Markdown a partir d'une chaine de texte."""
    return {"cell_type": "markdown", "id": gid(), "metadata": {}, "source": s}


def code(s):
    """Cree une cellule de code Python a partir d'une chaine de texte."""
    return {
        "cell_type": "code", "execution_count": None,
        "id": gid(), "metadata": {}, "outputs": [], "source": s,
    }

cells = []

# === TITRE ===
cells.append(md(
    "# Etapes 3 & 4 - Modelisation avec tracking MLflow\n\n"
    "Version MLflow de `modeling_local.ipynb` — memes modeles et metriques, "
    "chaque run est trace dans MLflow.\n\n"
    "**Etape 3** : baseline Dummy, LogReg, LightGBM.\n\n"
    "**Etape 4** : optimisation GridSearch / RandomizedSearch + runs finaux loggues.\n\n"
    "Metriques OOF au seuil optimal minimisant `10 x FN + FP`."
))

# === IMPORTS ===
cells.append(code(
"import os, sys, re, warnings\n"
"import numpy as np\n"
"import pandas as pd\n"
"import matplotlib.pyplot as plt\n"
"import seaborn as sns\n"
"from IPython.display import display\n"
"\n"
"import mlflow\n"
"import mlflow.sklearn\n"
"import mlflow.lightgbm\n"
"\n"
"from sklearn.model_selection import (\n"
"    StratifiedKFold, RandomizedSearchCV, GridSearchCV, train_test_split,\n"
")\n"
"from sklearn.metrics import (\n"
"    roc_auc_score, average_precision_score, roc_curve,\n"
"    f1_score, recall_score, precision_score, confusion_matrix,\n"
")\n"
"from sklearn.dummy import DummyClassifier\n"
"from sklearn.linear_model import LogisticRegression\n"
"from sklearn.impute import SimpleImputer\n"
"from sklearn.preprocessing import StandardScaler\n"
"from sklearn.pipeline import Pipeline\n"
"\n"
"import lightgbm as lgb\n"
"from lightgbm import LGBMClassifier\n"
"\n"
"warnings.filterwarnings('ignore')\n"
"sys.path.append(os.path.abspath('..'))\n"
"\n"
"from src.config import (\n"
"    RANDOM_STATE, N_FOLDS, TEST_SIZE, TARGET_COL, ID_COL,\n"
"    PROCESSED_DIR, MODELS_DIR, FIGURES_DIR, LGB_DEVICE,\n"
"    MLFLOW_TRACKING_URI, MLFLOW_EXPERIMENT_NAME,\n"
")\n"
"\n"
"print(f'Device  : {LGB_DEVICE}')\n"
"print(f'N_FOLDS : {N_FOLDS}  |  RANDOM_STATE : {RANDOM_STATE}')\n"
))

# === MLFLOW SETUP ===
cells.append(md("## 0. Configuration MLflow"))
cells.append(code(
"mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)\n"
"mlflow.set_experiment(MLFLOW_EXPERIMENT_NAME)\n"
"\n"
"print(f'Tracking URI : {MLFLOW_TRACKING_URI}')\n"
"print(f'Experiment   : {MLFLOW_EXPERIMENT_NAME}')\n"
))

# === CHARGEMENT ===
cells.append(md("## 1. Chargement des donnees"))
cells.append(code(
"train_df = pd.read_csv(PROCESSED_DIR / 'train_processed_global.csv')\n"
"print(f'Shape  : {train_df.shape}')\n"
"print(f'Defaut : {train_df[TARGET_COL].mean():.2%}')\n"
))

cells.append(code(
"COLS_EXCLUDE = [TARGET_COL, ID_COL, 'SK_ID_BUREAU', 'SK_ID_PREV', 'index']\n"
"features = [c for c in train_df.columns if c not in COLS_EXCLUDE]\n"
"\n"
"X = train_df[features].copy()\n"
"y = train_df[TARGET_COL].copy()\n"
"\n"
"# Nettoyage des noms de colonnes — LightGBM rejette les caracteres speciaux\n"
"X.columns = [re.sub(r'[^A-Za-z0-9_]+', '_', c) for c in X.columns]\n"
"\n"
"print(f'X : {X.shape}  |  Classes : {y.value_counts().to_dict()}')\n"
))

# === TRAIN / TEST SPLIT ===
cells.append(md(
    "## 1.1 Split train / test stratifie\n\n"
    "Separation **unique** avant tout entrainement. "
    "`X_test` et `y_test` ne servent qu'a l'evaluation finale non biaisee — "
    "jamais utilises pendant la CV ni le reglage des hyperparametres."
))
cells.append(code(
"# Split unique : ratio TEST_SIZE defini dans src/config.py\n"
"X_train, X_test, y_train, y_test = train_test_split(\n"
"    X, y,\n"
"    test_size=TEST_SIZE,\n"
"    stratify=y,\n"
"    random_state=RANDOM_STATE,\n"
")\n"
"\n"
"print(f'Train : {X_train.shape}  |  Test : {X_test.shape}')\n"
"print(f'Taux defaut  train : {y_train.mean():.2%}  |  test : {y_test.mean():.2%}')\n"
"\n"
"# Tags MLflow communs a tous les runs — documentent la methodologie\n"
"_SPLIT_TAGS = {\n"
"    'split_type': 'stratified',\n"
"    'test_size':  str(TEST_SIZE),\n"
"    'n_train':    str(len(X_train)),\n"
"    'n_test':     str(len(X_test)),\n"
"}\n"
))

# === HELPERS - METRIQUES ===
cells.append(md("## 2. Fonctions utilitaires"))
cells.append(code(
"def compute_business_cost(y_true, y_pred, fn_cost=10, fp_cost=1):\n"
"    \"\"\"Cout metier asymetrique : fn_cost * FN + fp_cost * FP.\n"
"\n"
"    Un defaillant manque (FN) coute 10x plus qu'un bon client refuse (FP).\n"
"    Retourne (cout_total, nb_fn, nb_fp).\n"
"    \"\"\"\n"
"    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()  # ordre sklearn : TN FP FN TP\n"
"    return fn_cost * fn + fp_cost * fp, int(fn), int(fp)\n"
"\n"
"\n"
"def find_best_threshold(y_true, y_proba, thresholds=None):\n"
"    \"\"\"Cherche le seuil de decision qui minimise le cout metier.\n"
"\n"
"    Parcourt les seuils de 0.01 a 0.98 par pas de 0.01.\n"
"    Retourne (seuil_optimal: float, cout_minimal: int).\n"
"    \"\"\"\n"
"    if thresholds is None:\n"
"        thresholds = np.arange(0.01, 0.99, 0.01)\n"
"    best_t, best_c = 0.5, float('inf')  # valeurs initiales : seuil neutre, cout infini\n"
"    for t in thresholds:\n"
"        c, _, _ = compute_business_cost(y_true, (y_proba >= t).astype(int))\n"
"        if c < best_c:  # mise a jour si ce seuil donne un cout plus faible\n"
"            best_c, best_t = c, t\n"
"    return round(float(best_t), 2), int(best_c)\n"
"\n"
"\n"
"def compute_all_metrics(name, y_true, y_proba, fold_aucs):\n"
"    \"\"\"Consolide toutes les metriques a partir des predictions OOF.\n"
"\n"
"    Calcule AUC, PR-AUC, Recall, Precision, F1 et cout metier au seuil optimal.\n"
"    Retourne un dict directement utilisable dans pd.DataFrame.\n"
"    \"\"\"\n"
"    thresh, cost = find_best_threshold(y_true, y_proba)      # seuil qui minimise le cout metier\n"
"    y_pred = (y_proba >= thresh).astype(int)                  # binarisation au seuil optimal\n"
"    _, fn, fp = compute_business_cost(y_true, y_pred)         # recalcul pour isoler FN et FP\n"
"    return {\n"
"        'Modele':      name,\n"
"        'AUC moy':     round(float(np.mean(fold_aucs)), 4),\n"
"        'AUC std':     round(float(np.std(fold_aucs)),  4),\n"
"        'PR-AUC':      round(float(average_precision_score(y_true, y_proba)), 4),\n"
"        'Recall':      round(float(recall_score(y_true, y_pred)),   4),\n"
"        'Precision':   round(float(precision_score(y_true, y_pred, zero_division=0)), 4),\n"
"        'F1':          round(float(f1_score(y_true, y_pred)),       4),\n"
"        'Seuil':       thresh,\n"
"        'Cout metier': cost,\n"
"        'FN':          fn,\n"
"        'FP':          fp,\n"
"    }\n"
"\n"
"print('Metriques chargees.')\n"
))

# === HELPERS - VISUALISATION ===
cells.append(code(
"def plot_roc_curves(models_probas, y_true, title='Courbes ROC'):\n"
"    \"\"\"Trace les courbes ROC de plusieurs modeles sur le meme graphique.\n"
"\n"
"    models_probas : dict {nom_modele: array de probabilites de la classe positive}\n"
"    Retourne la figure matplotlib pour le logging MLflow.\n"
"    \"\"\"\n"
"    fig, ax = plt.subplots(figsize=(8, 6))\n"
"    for name, proba in models_probas.items():\n"
"        fpr, tpr, _ = roc_curve(y_true, proba)  # taux de faux positifs et vrais positifs\n"
"        auc = roc_auc_score(y_true, proba)\n"
"        ax.plot(fpr, tpr, label=f'{name}  (AUC = {auc:.4f})')\n"
"    ax.plot([0, 1], [0, 1], '--', color='gray', label='Aleatoire (AUC = 0.5)')  # diagonale : classifieur aleatoire\n"
"    ax.set_xlabel('Taux Faux Positifs (FPR)')\n"
"    ax.set_ylabel('Taux Vrais Positifs (TPR)')\n"
"    ax.set_title(title)\n"
"    ax.legend(fontsize=9)\n"
"    ax.grid(True)\n"
"    fig.tight_layout()\n"
"    plt.show()\n"
"    return fig\n"
"\n"
"\n"
"def plot_threshold_curve(y_true, y_proba, model_name=''):\n"
"    \"\"\"Trace le cout metier en fonction du seuil de decision.\n"
"\n"
"    Marque le seuil optimal (minimum du cout) d'une ligne verticale rouge.\n"
"    Retourne la figure matplotlib pour le logging MLflow.\n"
"    \"\"\"\n"
"    thresholds = np.arange(0.01, 0.99, 0.01)\n"
"    costs = [\n"
"        compute_business_cost(y_true, (y_proba >= t).astype(int))[0]  # cout pour chaque seuil\n"
"        for t in thresholds\n"
"    ]\n"
"    best_t, best_c = find_best_threshold(y_true, y_proba)  # seuil optimal sur cette courbe\n"
"    fig, ax = plt.subplots(figsize=(9, 5))\n"
"    ax.plot(thresholds, costs, linewidth=2)\n"
"    ax.axvline(\n"
"        best_t, linestyle='--', color='red',\n"
"        label=f'Seuil optimal = {best_t:.2f}  ->  cout = {best_c:,}'\n"
"    )\n"
"    ax.set_xlabel('Seuil de decision')\n"
"    ax.set_ylabel('Cout metier  (10 x FN + FP)')\n"
"    ax.set_title(f'Cout metier vs Seuil - {model_name}')\n"
"    ax.legend()\n"
"    ax.grid(True)\n"
"    fig.tight_layout()\n"
"    plt.show()\n"
"    return fig\n"
"\n"
"\n"
"def display_results(df, title=''):\n"
"    \"\"\"Affiche le tableau de metriques avec mise en forme coloree.\n"
"\n"
"    Met en vert les meilleures valeurs (AUC, Recall, F1)\n"
"    et les couts les plus bas (Cout metier, FN, FP).\n"
"    \"\"\"\n"
"    if title:\n"
"        print(f\"{'='*60}\\n  {title}\\n{'='*60}\")\n"
"    styled = (\n"
"        df.style\n"
"        .highlight_max(subset=['AUC moy', 'PR-AUC', 'Recall', 'F1'], color='#c6efce')  # vert : valeurs les plus hautes\n"
"        .highlight_min(subset=['Cout metier', 'FN', 'FP'], color='#c6efce')             # vert : valeurs les plus basses\n"
"        .format({\n"
"            'AUC moy':   '{:.4f}',\n"
"            'AUC std':   '{:.4f}',\n"
"            'PR-AUC':    '{:.4f}',\n"
"            'Recall':    '{:.4f}',\n"
"            'Precision': '{:.4f}',\n"
"            'F1':        '{:.4f}',\n"
"        })\n"
"    )\n"
"    display(styled)\n"
"\n"
"print('Visualisation chargee.')\n"
))

# === HELPER - MLFLOW LOGGING ===
cells.append(code(
"def log_metrics_mlflow(metrics: dict):\n"
"    \"\"\"Enregistre les metriques OOF dans le run MLflow actif.\n"
"\n"
"    metrics : dict retourne par compute_all_metrics().\n"
"    Doit etre appele a l'interieur d'un bloc mlflow.start_run().\n"
"    \"\"\"\n"
"    # Noms de cles normalises : minuscules, sans accents ni espaces (convention MLflow)\n"
"    mlflow.log_metrics({\n"
"        'auc_mean':    metrics['AUC moy'],     # moyenne des AUC par fold\n"
"        'auc_std':     metrics['AUC std'],     # ecart-type : mesure la stabilite entre folds\n"
"        'pr_auc':      metrics['PR-AUC'],      # aire sous la courbe Precision-Recall\n"
"        'recall':      metrics['Recall'],      # taux de detection des defaillants\n"
"        'precision':   metrics['Precision'],\n"
"        'f1':          metrics['F1'],\n"
"        'seuil':       float(metrics['Seuil']),\n"
"        'cout_metier': float(metrics['Cout metier']),\n"
"        'fn':          float(metrics['FN']),   # defaillants manques (erreur la plus couteuse)\n"
"        'fp':          float(metrics['FP']),   # bons clients refuses\n"
"    })\n"
"\n"
"print('Helper MLflow charge.')\n"
))

# === CV FUNCTIONS ===
cells.append(md("## 3. Fonctions de validation croisee"))
cells.append(code(
"def cv_sklearn(name, make_model, X, y, needs_scaling=False, verbose=True):\n"
"    \"\"\"Validation croisee StratifiedKFold pour les modeles scikit-learn.\n"
"\n"
"    make_model  : callable sans argument retournant un estimateur frais a chaque fold.\n"
"    needs_scaling : si True, applique SimpleImputer + StandardScaler dans chaque fold\n"
"                    (fit uniquement sur les donnees d'entrainement du fold).\n"
"    Retourne (metriques: dict, oof_proba: np.ndarray).\n"
"    \"\"\"\n"
"    skf  = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_STATE)\n"
"    oof  = np.zeros(len(y))  # contiendra les probabilites predites sur les folds de validation\n"
"    aucs = []                # AUC de chaque fold, pour calculer moyenne et ecart-type\n"
"\n"
"    for fold, (tr, val) in enumerate(skf.split(X, y), 1):\n"
"        X_tr, X_val = X.values[tr], X.values[val]\n"
"        y_tr, y_val = y.values[tr], y.values[val]\n"
"\n"
"        if needs_scaling:\n"
"            # Imputation et standardisation fitees sur X_tr uniquement — evite la fuite de donnees\n"
"            imp   = SimpleImputer(strategy='median')\n"
"            X_tr  = imp.fit_transform(X_tr)\n"
"            X_val = imp.transform(X_val)\n"
"            sc    = StandardScaler()\n"
"            X_tr  = sc.fit_transform(X_tr)\n"
"            X_val = sc.transform(X_val)\n"
"\n"
"        model = make_model()  # nouvel estimateur a chaque fold pour eviter toute fuite\n"
"        model.fit(X_tr, y_tr)\n"
"        oof[val] = model.predict_proba(X_val)[:, 1]  # probabilite classe positive (defaut)\n"
"\n"
"        auc = roc_auc_score(y_val, oof[val])\n"
"        aucs.append(auc)\n"
"        if verbose:\n"
"            print(f'  Fold {fold}/{N_FOLDS}  AUC = {auc:.4f}')\n"
"\n"
"    metrics = compute_all_metrics(name, y, oof, aucs)\n"
"    print(f\"  -> OOF AUC = {metrics['AUC moy']:.4f} +/- {metrics['AUC std']:.4f}\")\n"
"    return metrics, oof\n"
"\n"
"\n"
"def cv_lgbm(name, params, X, y, verbose=True):\n"
"    \"\"\"Validation croisee StratifiedKFold pour LightGBM avec early stopping.\n"
"\n"
"    L'early stopping arrete l'entrainement apres 100 rounds sans amelioration\n"
"    de l'AUC sur le fold de validation, evitant le sur-apprentissage.\n"
"    Retourne (metriques: dict, oof_proba: np.ndarray).\n"
"    \"\"\"\n"
"    skf  = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_STATE)\n"
"    oof  = np.zeros(len(y))  # contiendra les probabilites predites sur les folds de validation\n"
"    aucs = []                # AUC de chaque fold\n"
"\n"
"    for fold, (tr, val) in enumerate(skf.split(X, y), 1):\n"
"        X_tr, X_val = X.iloc[tr], X.iloc[val]\n"
"        y_tr, y_val = y.iloc[tr], y.iloc[val]\n"
"\n"
"        model = LGBMClassifier(**params)\n"
"        model.fit(\n"
"            X_tr, y_tr,\n"
"            eval_set=[(X_val, y_val)],  # jeu de validation pour surveiller la convergence\n"
"            eval_metric='auc',\n"
"            callbacks=[\n"
"                lgb.early_stopping(stopping_rounds=100, verbose=False),  # arrete si pas de progres sur 100 rounds\n"
"                lgb.log_evaluation(period=-1),  # desactive les logs LightGBM internes\n"
"            ],\n"
"        )\n"
"        oof[val] = model.predict_proba(X_val)[:, 1]  # probabilite classe positive (defaut)\n"
"        auc      = roc_auc_score(y_val, oof[val])\n"
"        aucs.append(auc)\n"
"        if verbose:\n"
"            print(f'  Fold {fold}/{N_FOLDS}  AUC = {auc:.4f}  '\n"
"                  f'(meilleure iteration = {model.best_iteration_})')\n"
"\n"
"    metrics = compute_all_metrics(name, y, oof, aucs)\n"
"    print(f\"  -> OOF AUC = {metrics['AUC moy']:.4f} +/- {metrics['AUC std']:.4f}\")\n"
"    return metrics, oof\n"
"\n"
"print('Fonctions CV chargees.')\n"
))

# === ETAPE 3 ===
cells.append(md(
    "---\n"
    "## Etape 3 - Comparaison des modeles baseline\n\n"
    "Chaque modele est trace dans un run MLflow distinct. "
    "Tag `etape=3`, `model_type=baseline`."
))

# Dummy
cells.append(md("### Modele 1 : Dummy Classifier"))
cells.append(code(
"with mlflow.start_run(run_name='Dummy_baseline'):\n"
"    mlflow.set_tag('model_type', 'baseline')\n"
"    mlflow.set_tags(_SPLIT_TAGS)\n"
"\n"
"    print('=== Dummy Classifier ===')\n"
"    dummy_metrics, dummy_proba = cv_sklearn(\n"
"        'Dummy',\n"
"        lambda: DummyClassifier(strategy='prior', random_state=RANDOM_STATE),\n"
"        X_train, y_train,\n"
"    )\n"
"    log_metrics_mlflow(dummy_metrics)\n"
"    print('Run MLflow : Dummy_baseline enregistre.')\n"
))

# LR baseline
cells.append(md("### Modele 2 : Logistic Regression baseline"))
cells.append(code(
"LR_BASELINE_PARAMS = {\n"
"    'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs',\n"
"    'class_weight': 'balanced', 'max_iter': 1000,\n"
"}\n"
"\n"
"with mlflow.start_run(run_name='LR_baseline'):\n"
"    mlflow.set_tag('model_type', 'baseline')\n"
"    mlflow.set_tags(_SPLIT_TAGS)\n"
"    mlflow.log_params({'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'})\n"
"\n"
"    print('=== Logistic Regression baseline ===')\n"
"    logreg_metrics, logreg_proba = cv_sklearn(\n"
"        'Logistic Regression',\n"
"        lambda: LogisticRegression(**LR_BASELINE_PARAMS, random_state=RANDOM_STATE, n_jobs=1),\n"
"        X_train, y_train, needs_scaling=True,\n"
"    )\n"
"    log_metrics_mlflow(logreg_metrics)\n"
"    print('Run MLflow : LR_baseline enregistre.')\n"
))

# LightGBM baseline
cells.append(md("### Modele 3 : LightGBM baseline"))
cells.append(code(
"LGBM_BASE_PARAMS = {\n"
"    'n_estimators':      1000,\n"
"    'learning_rate':     0.05,\n"
"    'num_leaves':        31,\n"
"    'max_depth':         -1,\n"
"    'min_child_samples': 20,\n"
"    'subsample':         0.8,\n"
"    'colsample_bytree':  0.8,\n"
"    'reg_alpha':         0.0,\n"
"    'reg_lambda':        0.0,\n"
"    'objective':         'binary',\n"
"    'class_weight':      'balanced',\n"
"    'random_state':      RANDOM_STATE,\n"
"    'n_jobs':            1,\n"
"    'verbosity':         -1,\n"
"    'device':            LGB_DEVICE,\n"
"}\n"
"\n"
"with mlflow.start_run(run_name='LightGBM_baseline'):\n"
"    mlflow.set_tag('model_type', 'baseline')\n"
"    mlflow.set_tags(_SPLIT_TAGS)\n"
"    # Exclusion des parametres techniques non pertinents pour le tracking\n"
"    _exclude = ('n_jobs', 'verbosity', 'objective', 'random_state')\n"
"    mlflow.log_params({k: v for k, v in LGBM_BASE_PARAMS.items() if k not in _exclude})\n"
"\n"
"    print('=== LightGBM baseline ===')\n"
"    lgbm_metrics, lgbm_proba = cv_lgbm('LightGBM baseline', LGBM_BASE_PARAMS, X_train, y_train)\n"
"    log_metrics_mlflow(lgbm_metrics)\n"
"    print('Run MLflow : LightGBM_baseline enregistre.')\n"
))

# Step 3 results
cells.append(md("### Resultats Etape 3"))
cells.append(code(
"results_step3 = pd.DataFrame(\n"
"    [dummy_metrics, logreg_metrics, lgbm_metrics]\n"
").set_index('Modele')\n"
"\n"
"display_results(results_step3, 'Etape 3 - Comparaison des modeles')\n"
"\n"
"fig_roc3 = plot_roc_curves(\n"
"    {\n"
"        'Dummy':               dummy_proba,\n"
"        'Logistic Regression': logreg_proba,\n"
"        'LightGBM baseline':   lgbm_proba,\n"
"    },\n"
"    y_train, title='Etape 3 - Courbes ROC (OOF sur X_train)',\n"
")\n"
"fig_roc3.savefig(FIGURES_DIR / 'roc_step3.png', dpi=150, bbox_inches='tight')\n"
"plt.close(fig_roc3)\n"
"print('Figure sauvegardee : roc_step3.png')\n"
))

# === ETAPE 4 ===
cells.append(md(
    "---\n"
    "## Etape 4 - Optimisation des hyperparametres\n\n"
    "- **Logistic Regression** -> `GridSearchCV` sur 20% du dataset\n"
    "- **LightGBM** -> `RandomizedSearchCV` (30 combinaisons) puis `GridSearchCV` (fine-tuning)\n\n"
    "Les runs MLflow sont crees uniquement pour les CV finales (section 4.4)."
))

# 4.1 LR GridSearch
cells.append(md("### 4.1 Logistic Regression - GridSearchCV"))
cells.append(code(
"X_srch, _, y_srch, _ = train_test_split(\n"
"    X_train, y_train, train_size=0.2, stratify=y_train, random_state=RANDOM_STATE\n"
")\n"
"print(f'Taille du sous-echantillon : {X_srch.shape}')\n"
"\n"
"lr_pipeline = Pipeline([\n"
"    ('imputer', SimpleImputer(strategy='median')),\n"
"    ('scaler',  StandardScaler()),\n"
"    ('lr',      LogisticRegression(\n"
"        max_iter=1000, class_weight='balanced',\n"
"        random_state=RANDOM_STATE, n_jobs=1,\n"
"    )),\n"
"])\n"
"\n"
"param_grid_lr = {\n"
"    'lr__C':       [0.001, 0.01, 0.1],\n"
"    'lr__penalty': ['l2'],\n"
"    'lr__solver':  ['liblinear'],\n"
"}\n"
"\n"
"skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_STATE)\n"
"\n"
"gs_lr = GridSearchCV(\n"
"    lr_pipeline, param_grid_lr,\n"
"    cv=skf, scoring='roc_auc',\n"
"    n_jobs=1, verbose=2,\n"
")\n"
"gs_lr.fit(X_srch, y_srch)\n"
"\n"
"print(f'\\nMeilleurs params : {gs_lr.best_params_}')\n"
"print(f'Meilleur AUC CV  : {gs_lr.best_score_:.4f}')\n"
"\n"
"best_lr_params = {k.replace('lr__', ''): v for k, v in gs_lr.best_params_.items()}\n"
"print(f'Params nets      : {best_lr_params}')\n"
))

# 4.2 LightGBM RandomizedSearch
cells.append(md("### 4.2 LightGBM - RandomizedSearchCV"))
cells.append(code(
"lgb_param_dist = {\n"
"    'n_estimators':      [300, 500],\n"
"    'learning_rate':     [0.05, 0.1],\n"
"    'num_leaves':        [31, 63, 100],\n"
"    'min_child_samples': [20, 50, 100],\n"
"    'subsample':         [0.6, 0.8, 1.0],\n"
"    'colsample_bytree':  [0.6, 0.8, 1.0],\n"
"    'reg_lambda':        [0, 0.1, 1.0],\n"
"    'class_weight':      ['balanced'],\n"
"}\n"
"\n"
"lgb_for_search = LGBMClassifier(\n"
"    objective='binary', max_depth=-1,\n"
"    random_state=RANDOM_STATE,\n"
"    n_jobs=1, verbosity=-1, device=LGB_DEVICE,\n"
")\n"
"\n"
"random_lgb = RandomizedSearchCV(\n"
"    lgb_for_search, lgb_param_dist,\n"
"    n_iter=30, cv=skf, scoring='roc_auc',\n"
"    random_state=RANDOM_STATE, n_jobs=1, verbose=1,\n"
")\n"
"random_lgb.fit(X_train, y_train)\n"
"\n"
"print(f'\\nMeilleur AUC RandomizedSearch : {random_lgb.best_score_:.4f}')\n"
"print(f'Meilleurs params              : {random_lgb.best_params_}')\n"
))

# 4.3 LightGBM GridSearch fine-tuning
cells.append(md("### 4.3 LightGBM - GridSearchCV (fine-tuning)"))
cells.append(code(
"best_rnd = random_lgb.best_params_\n"
"\n"
"grid_lgb_params = {\n"
"    'n_estimators':  [best_rnd['n_estimators']],\n"
"    'learning_rate': [best_rnd['learning_rate']],\n"
"    'num_leaves': [\n"
"        max(4,   best_rnd['num_leaves'] // 2),\n"
"        best_rnd['num_leaves'],\n"
"        min(255, best_rnd['num_leaves'] * 2),\n"
"    ],\n"
"    'min_child_samples': [\n"
"        max(10, best_rnd['min_child_samples'] // 2),\n"
"        best_rnd['min_child_samples'],\n"
"        best_rnd['min_child_samples'] * 2,\n"
"    ],\n"
"    'subsample':        [best_rnd['subsample']],\n"
"    'colsample_bytree': [best_rnd['colsample_bytree']],\n"
"    'reg_lambda':       [best_rnd['reg_lambda']],\n"
"    'class_weight':     ['balanced'],\n"
"}\n"
"\n"
"grid_lgb = GridSearchCV(\n"
"    lgb_for_search, grid_lgb_params,\n"
"    cv=skf, scoring='roc_auc',\n"
"    n_jobs=1, verbose=2,\n"
")\n"
"grid_lgb.fit(X_train, y_train)\n"
"\n"
"print(f'\\nMeilleur AUC GridSearch : {grid_lgb.best_score_:.4f}')\n"
"print(f'Meilleurs params        : {grid_lgb.best_params_}')\n"
"\n"
"# n_estimators remis a 1000 : l'early stopping le limitera en CV finale\n"
"LGBM_BEST_PARAMS = {\n"
"    **grid_lgb.best_params_,\n"
"    'objective':    'binary',\n"
"    'max_depth':    -1,\n"
"    'random_state': RANDOM_STATE,\n"
"    'n_jobs':       1,\n"
"    'verbosity':    -1,\n"
"    'device':       LGB_DEVICE,\n"
"    'n_estimators': 1000,\n"
"}\n"
"print(f'\\nParametres finaux LightGBM : {LGBM_BEST_PARAMS}')\n"
))

# 4.4 CV finale + MLflow runs
cells.append(md("### 4.4 CV finale - Logistic Regression optimisee"))
cells.append(code(
"with mlflow.start_run(run_name='LR_optimise'):\n"
"    mlflow.set_tag('model_type', 'optimise')\n"
"    mlflow.set_tags(_SPLIT_TAGS)\n"
"    mlflow.log_params(best_lr_params)\n"
"\n"
"    print('=== Logistic Regression optimisee ===')\n"
"    logreg_opt_metrics, logreg_opt_proba = cv_sklearn(\n"
"        'LR optimisee',\n"
"        lambda: LogisticRegression(\n"
"            **best_lr_params, max_iter=1000,\n"
"            class_weight='balanced',\n"
"            random_state=RANDOM_STATE, n_jobs=1,\n"
"        ),\n"
"        X_train, y_train, needs_scaling=True,\n"
"    )\n"
"    log_metrics_mlflow(logreg_opt_metrics)\n"
"\n"
"    # Evaluation sur le jeu de test (non vu pendant la CV)\n"
"    final_lr = Pipeline([\n"
"        ('imputer', SimpleImputer(strategy='median')),\n"
"        ('scaler',  StandardScaler()),\n"
"        ('lr',      LogisticRegression(\n"
"            **best_lr_params, max_iter=1000,\n"
"            class_weight='balanced',\n"
"            random_state=RANDOM_STATE, n_jobs=1,\n"
"        )),\n"
"    ])\n"
"    final_lr.fit(X_train, y_train)\n"
"    lr_test_proba = final_lr.predict_proba(X_test)[:, 1]\n"
"    auc_test_lr   = roc_auc_score(y_test, lr_test_proba)\n"
"    gap_lr        = round(logreg_opt_metrics['AUC moy'] - auc_test_lr, 4)\n"
"    mlflow.log_metric('auc_test',     round(auc_test_lr, 4))\n"
"    mlflow.log_metric('gap_oof_test', gap_lr)\n"
"    print(f'AUC OOF : {logreg_opt_metrics[\"AUC moy\"]:.4f}  |  AUC Test : {auc_test_lr:.4f}  |  Gap : {gap_lr:.4f}')\n"
"\n"
"    # Reentretainement sur tout le dataset pour la production\n"
"    final_lr.fit(X, y)\n"
"    mlflow.sklearn.log_model(\n"
"        final_lr, 'model',\n"
"        registered_model_name='LR_credit_scoring',\n"
"    )\n"
"\n"
"    fig_thr_lr = plot_threshold_curve(y_train, logreg_opt_proba, 'LR optimisee')\n"
"    mlflow.log_figure(fig_thr_lr, 'threshold_curve.png')\n"
"    fig_thr_lr.savefig(FIGURES_DIR / 'threshold_lr_opt.png', dpi=150, bbox_inches='tight')\n"
"    plt.close(fig_thr_lr)\n"
"\n"
"    print('Run MLflow : LR_optimise enregistre.')\n"
))

cells.append(md("### 4.4 CV finale - LightGBM optimise"))
cells.append(code(
"with mlflow.start_run(run_name='LightGBM_optimise'):\n"
"    mlflow.set_tag('model_type', 'optimise')\n"
"    mlflow.set_tags(_SPLIT_TAGS)\n"
"    _exclude = ('n_jobs', 'verbosity', 'objective', 'random_state')\n"
"    mlflow.log_params({k: v for k, v in LGBM_BEST_PARAMS.items() if k not in _exclude})\n"
"\n"
"    print('=== LightGBM optimise ===')\n"
"    lgbm_opt_metrics, lgbm_opt_proba = cv_lgbm(\n"
"        'LightGBM optimise', LGBM_BEST_PARAMS, X_train, y_train\n"
"    )\n"
"    log_metrics_mlflow(lgbm_opt_metrics)\n"
"\n"
"    # Evaluation sur le jeu de test (non vu pendant la CV)\n"
"    final_lgbm = LGBMClassifier(**LGBM_BEST_PARAMS)\n"
"    final_lgbm.fit(X_train, y_train)\n"
"    lgbm_test_proba = final_lgbm.predict_proba(X_test)[:, 1]\n"
"    auc_test_lgbm   = roc_auc_score(y_test, lgbm_test_proba)\n"
"    gap_lgbm        = round(lgbm_opt_metrics['AUC moy'] - auc_test_lgbm, 4)\n"
"    mlflow.log_metric('auc_test',     round(auc_test_lgbm, 4))\n"
"    mlflow.log_metric('gap_oof_test', gap_lgbm)\n"
"    print(f'AUC OOF : {lgbm_opt_metrics[\"AUC moy\"]:.4f}  |  AUC Test : {auc_test_lgbm:.4f}  |  Gap : {gap_lgbm:.4f}')\n"
"\n"
"    # Reentretainement sur tout le dataset pour la production\n"
"    final_lgbm.fit(X, y)\n"
"    mlflow.lightgbm.log_model(\n"
"        final_lgbm, 'model',\n"
"        registered_model_name='LightGBM_credit_scoring',\n"
"    )\n"
"\n"
"    # Courbes loggees comme artefacts du run\n"
"    fig_thr_lgbm = plot_threshold_curve(y_train, lgbm_opt_proba, 'LightGBM optimise')\n"
"    mlflow.log_figure(fig_thr_lgbm, 'threshold_curve.png')\n"
"    fig_thr_lgbm.savefig(FIGURES_DIR / 'threshold_lgbm_opt.png', dpi=150, bbox_inches='tight')\n"
"    plt.close(fig_thr_lgbm)\n"
"\n"
"    fig_roc_opt = plot_roc_curves(\n"
"        {'LR optimisee': logreg_opt_proba, 'LightGBM optimise': lgbm_opt_proba},\n"
"        y_train, title='Etape 4 - Courbes ROC (OOF sur X_train)',\n"
"    )\n"
"    mlflow.log_figure(fig_roc_opt, 'roc_curve_optimises.png')\n"
"    fig_roc_opt.savefig(FIGURES_DIR / 'roc_step4.png', dpi=150, bbox_inches='tight')\n"
"    plt.close(fig_roc_opt)\n"
"\n"
"    print('Run MLflow : LightGBM_optimise enregistre.')\n"
))

# Resultats finaux
cells.append(md("### Resultats finaux - Etapes 3 & 4"))
cells.append(code(
"all_results = pd.DataFrame([\n"
"    dummy_metrics,\n"
"    logreg_metrics,\n"
"    logreg_opt_metrics,\n"
"    lgbm_metrics,\n"
"    lgbm_opt_metrics,\n"
"]).set_index('Modele')\n"
"\n"
"display_results(all_results, 'Resultats finaux - tous les modeles')\n"
"\n"
"fig_roc_all = plot_roc_curves(\n"
"    {\n"
"        'Dummy':              dummy_proba,\n"
"        'LR baseline':        logreg_proba,\n"
"        'LR optimisee':       logreg_opt_proba,\n"
"        'LightGBM baseline':  lgbm_proba,\n"
"        'LightGBM optimise':  lgbm_opt_proba,\n"
"    },\n"
"    y_train, title='Etapes 3 & 4 - Courbes ROC (OOF sur X_train)',\n"
")\n"
"fig_roc_all.savefig(FIGURES_DIR / 'roc_all.png', dpi=150, bbox_inches='tight')\n"
"plt.close(fig_roc_all)\n"
"print('Figures sauvegardees dans reports/figures/')\n"
))

# === MATRICE DE CONFUSION ===
cells.append(md(
    "---\n"
    "## 5. Matrice de confusion — LightGBM optimise\n\n"
    "Calculee sur le **jeu de test** (`X_test`, `y_test`) au **seuil optimal** "
    "trouve sur les predictions OOF — evaluation non biaisee sur des donnees jamais vues."
))
cells.append(code(
"from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix\n"
"from src.config import FIGURES_DIR\n"
"\n"
"# Seuil trouve sur les predictions OOF (X_train), applique au jeu de test\n"
"thresh_lgbm     = lgbm_opt_metrics['Seuil']\n"
"y_pred_lgbm_tst = (lgbm_test_proba >= thresh_lgbm).astype(int)\n"
"\n"
"cm = confusion_matrix(y_test, y_pred_lgbm_tst)\n"
"tn, fp, fn, tp = cm.ravel()\n"
"\n"
"# Figure\n"
"fig_cm, ax = plt.subplots(figsize=(6, 5))\n"
"disp = ConfusionMatrixDisplay(\n"
"    confusion_matrix=cm,\n"
"    display_labels=['Non defaillant (0)', 'Defaillant (1)'],\n"
")\n"
"disp.plot(ax=ax, colorbar=False, cmap='Blues')\n"
"ax.set_title(\n"
"    f'Matrice de confusion — LightGBM optimise\\n'\n"
"    f'Seuil = {thresh_lgbm:.2f}  |  jeu de test ({len(y_test):,} clients)',\n"
"    fontsize=12,\n"
")\n"
"plt.tight_layout()\n"
"plt.show()\n"
"\n"
"# Resume chiffre\n"
"print(f'\\nSeuil optimal (OOF) : {thresh_lgbm:.2f}')\n"
"print(f'VP (True Pos.)      : {tp:>8,}  — defaillants detectes')\n"
"print(f'FN (False Neg.)     : {fn:>8,}  — defaillants manques  [cout x10]')\n"
"print(f'FP (False Pos.)     : {fp:>8,}  — bons clients refuses [cout x1]')\n"
"print(f'VN (True Neg.)      : {tn:>8,}  — bons clients acceptes')\n"
"print(f'\\nCout metier         : {10*fn + fp:,}')\n"
"print(f'Recall              : {tp/(tp+fn):.4f}')\n"
"print(f'Precision           : {tp/(tp+fp):.4f}')\n"
"\n"
"# Tracking MLflow\n"
"with mlflow.start_run(run_name='LightGBM_confusion_matrix'):\n"
"    mlflow.set_tag('model_type', 'evaluation')\n"
"    mlflow.set_tags(_SPLIT_TAGS)\n"
"    mlflow.log_param('threshold', thresh_lgbm)\n"
"    mlflow.log_param('eval_set',  'test')\n"
"    mlflow.log_metrics({\n"
"        'tp': int(tp), 'tn': int(tn),\n"
"        'fp': int(fp), 'fn': int(fn),\n"
"        'cout_metier': int(10*fn + fp),\n"
"        'auc_test':    round(auc_test_lgbm, 4),\n"
"    })\n"
"    mlflow.log_figure(fig_cm, 'confusion_matrix.png')\n"
"    fig_cm.savefig(FIGURES_DIR / 'confusion_matrix_lgbm.png', dpi=150, bbox_inches='tight')\n"
"    plt.close(fig_cm)\n"
"    print('\\nRun MLflow : LightGBM_confusion_matrix enregistre.')\n"
))

# Sauvegarde .pkl
cells.append(md("## 6. Sauvegarde locale des modeles (.pkl)"))
cells.append(code(
"import joblib\n"
"\n"
"# Sauvegarde locale en complement du stockage MLflow\n"
"lr_path   = MODELS_DIR / 'lr_optimized.pkl'\n"
"lgbm_path = MODELS_DIR / 'lgbm_optimized.pkl'\n"
"\n"
"joblib.dump(final_lr,   lr_path)\n"
"joblib.dump(final_lgbm, lgbm_path)\n"
"\n"
"print(f'LR   : {lr_path}')\n"
"print(f'LGBM : {lgbm_path}')\n"
))

# === SHAP ===
cells.append(md(
    "---\n"
    "## 7. Feature Importance — SHAP\n\n"
    "SHAP (SHapley Additive exPlanations) quantifie la contribution de chaque "
    "feature aux predictions du modele LightGBM final.\n\n"
    "Les colonnes issues du one-hot encoding sont **regroupees** par variable "
    "d'origine (via `original_categorical_columns.csv`) pour ne pas diluer leur "
    "importance globale.\n\n"
    "Calcul sur un echantillon de 5 000 lignes pour la rapidite."
))

# 6.1 Group mapping
cells.append(code(
"import shap\n"
"from src.config import FIGURES_DIR, PROCESSED_DIR\n"
"\n"
"# Colonnes categorielles avant encodage — genere par feature_engineering.py\n"
"_cat_df = pd.read_csv(PROCESSED_DIR / 'original_categorical_columns.csv')\n"
"original_cat_cols = _cat_df['original_categorical_column'].unique().tolist()\n"
"\n"
"# Mapping : variable d'origine -> colonnes one-hot encodees dans X\n"
"group_mapping = {}\n"
"for _col in original_cat_cols:\n"
"    _matches = [c for c in X_train.columns if c.startswith(_col + '_')]\n"
"    if _matches:\n"
"        group_mapping[_col] = _matches\n"
"\n"
"print(f'{len(group_mapping)} variables categorielless avec one-hot dans X.')\n"
))

# 6.2 Compute SHAP values
cells.append(code(
"# Echantillon sur X_train uniquement — le jeu de test reste reserve a l'evaluation\n"
"SHAP_SAMPLE = 5_000\n"
"X_shap = X_train.sample(SHAP_SAMPLE, random_state=RANDOM_STATE)\n"
"y_shap = y_train.loc[X_shap.index]\n"
"\n"
"# TreeExplainer : optimise pour les modeles a base d'arbres\n"
"explainer   = shap.TreeExplainer(final_lgbm)\n"
"shap_values = explainer.shap_values(X_shap)\n"
"\n"
"# LightGBM binaire peut retourner une liste [classe 0, classe 1]\n"
"if isinstance(shap_values, list):\n"
"    shap_values = shap_values[1]\n"
"\n"
"shap_df = pd.DataFrame(shap_values, columns=X_shap.columns)\n"
"print(f'shap_df : {shap_df.shape}  (echantillon : {SHAP_SAMPLE} lignes)')\n"
))

# 6.3 Group one-hot + importance table
cells.append(code(
"# ── Regroupement one-hot -> variable d'origine ────────────────────────────\n"
"abs_shap_df  = shap_df.abs()\n"
"one_hot_cols = set()\n"
"grouped_series = []\n"
"\n"
"for _col, _encoded in group_mapping.items():\n"
"    _present = list(set(_encoded) & set(abs_shap_df.columns))\n"
"    if _present:\n"
"        one_hot_cols.update(_present)\n"
"        # Somme des contributions de toutes les modalites d'une meme variable\n"
"        grouped_series.append(\n"
"            abs_shap_df[_present].sum(axis=1).rename(_col)\n"
"        )\n"
"\n"
"# Variables continues : conservees telles quelles\n"
"_non_ohe = [c for c in abs_shap_df.columns if c not in one_hot_cols]\n"
"grouped_series.append(abs_shap_df[_non_ohe])\n"
"\n"
"grouped_shap_df = pd.concat(grouped_series, axis=1)\n"
"\n"
"# Importance globale = moyenne des |valeurs SHAP| par feature\n"
"shap_importance = (\n"
"    grouped_shap_df.mean()\n"
"    .sort_values(ascending=False)\n"
"    .reset_index()\n"
")\n"
"shap_importance.columns = ['feature', 'mean_abs_shap']\n"
"display(shap_importance.head(20))\n"
))

# 6.4 Beeswarm plot
cells.append(code(
"# ── Summary plot (beeswarm) — features brutes, top 15 ─────────────────────\n"
"# show=False : laisse matplotlib geree la figure sans l'afficher immediatement\n"
"shap.summary_plot(shap_values, X_shap, max_display=15, show=False)\n"
"fig_shap_beeswarm = plt.gcf()\n"
"plt.title('Feature Importance — SHAP beeswarm (top 15)', fontsize=13)\n"
"plt.tight_layout()\n"
"plt.show()\n"
))

# 6.5 Bar chart grouped
cells.append(code(
"# ── Bar chart — top 20 features regroupees ────────────────────────────────\n"
"_top20 = shap_importance.head(20)\n"
"fig_shap_bar, ax = plt.subplots(figsize=(10, 8))\n"
"ax.barh(\n"
"    _top20['feature'][::-1].values,\n"
"    _top20['mean_abs_shap'][::-1].values,\n"
"    color='#2D6AB5', edgecolor='white',\n"
")\n"
"ax.set_xlabel('Importance SHAP moyenne  (|valeur de Shapley|)')\n"
"ax.set_title('Top 20 features — SHAP regroupe (one-hot -> variable d\\'origine)')\n"
"ax.spines[['top', 'right']].set_visible(False)\n"
"fig_shap_bar.tight_layout()\n"
"plt.show()\n"
))

# 6.6 SHAP local — waterfall plots
cells.append(md(
    "### 6.6 SHAP local — Analyse individuelle\n\n"
    "Waterfall plot pour **un client non defaillant** (TARGET=0) "
    "et **un client defaillant** (TARGET=1).\n\n"
    "Chaque barre montre la contribution d'une feature a l'ecart entre "
    "la prediction individuelle et la valeur de base E[f(X)]."
))
cells.append(code(
"# shap.Explanation — objet requis pour les waterfall plots\n"
"shap_explanation = explainer(X_shap)\n"
"\n"
"# LightGBM binaire peut retourner shape (n, features, 2) -> classe positive\n"
"if len(shap_explanation.shape) == 3:\n"
"    shap_explanation = shap_explanation[:, :, 1]\n"
"\n"
"# Probabilites predites sur l'echantillon SHAP\n"
"y_proba_shap = final_lgbm.predict_proba(X_shap)[:, 1]\n"
"\n"
"# Client non defaillant : TARGET=0 ET probabilite predite < 20%\n"
"_mask_non_def = (y_shap.values == 0) & (y_proba_shap < 0.20)\n"
"if _mask_non_def.sum() == 0:\n"
"    print('Aucun client TARGET=0 avec proba < 20% — seuil releve a 40%')\n"
"    _mask_non_def = (y_shap.values == 0) & (y_proba_shap < 0.40)\n"
"_candidates_nd = np.where(_mask_non_def)[0]\n"
"# Parmi les candidats, on prend celui avec la probabilite la plus basse\n"
"idx_non_def = int(_candidates_nd[np.argmin(y_proba_shap[_candidates_nd])])\n"
"print(f'Client non defaillant selectionne — proba predite : {y_proba_shap[idx_non_def]:.4f}  (TARGET = {y_shap.iloc[idx_non_def]})')\n"
"\n"
"# Client defaillant : TARGET=1 ET probabilite predite > 53%\n"
"_mask_def = (y_shap.values == 1) & (y_proba_shap > 0.53)\n"
"if _mask_def.sum() == 0:\n"
"    print('Aucun client TARGET=1 avec proba > 53% — seuil abaisse a 30%')\n"
"    _mask_def = (y_shap.values == 1) & (y_proba_shap > 0.30)\n"
"_candidates = np.where(_mask_def)[0]\n"
"# Parmi les candidats, on prend celui avec la probabilite la plus elevee\n"
"idx_def = int(_candidates[np.argmax(y_proba_shap[_candidates])])\n"
"print(f'Client defaillant selectionne — proba predite : {y_proba_shap[idx_def]:.4f}  (TARGET = {y_shap.iloc[idx_def]})')\n"
"\n"
"fig_wf_non_def = None\n"
"fig_wf_def     = None\n"
"\n"
"for label, idx, cible in [\n"
"    ('Non defaillant', idx_non_def, 0),\n"
"    ('Defaillant',     idx_def,     1),\n"
"]:\n"
"    shap.plots.waterfall(shap_explanation[idx], max_display=12, show=False)\n"
"    fig = plt.gcf()\n"
"    plt.suptitle(\n"
"        f'SHAP local — {label}  (TARGET = {cible})',\n"
"        fontsize=12, fontweight='bold', y=1.01,\n"
"    )\n"
"    plt.tight_layout()\n"
"    plt.show()\n"
"    if cible == 0:\n"
"        fig_wf_non_def = fig\n"
"    else:\n"
"        fig_wf_def = fig\n"
))

# 6.7 MLflow SHAP run
cells.append(code(
"# ── Tracking MLflow ───────────────────────────────────────────────────────\n"
"with mlflow.start_run(run_name='LightGBM_SHAP'):\n"
"    mlflow.set_tag('model_type',  'interpretabilite')\n"
"    mlflow.set_tags(_SPLIT_TAGS)\n"
"    mlflow.log_param('n_shap_samples', SHAP_SAMPLE)\n"
"    mlflow.log_param('shap_explainer', 'TreeExplainer')\n"
"    mlflow.log_param('n_features_top', 20)\n"
"\n"
"    # Figures globales\n"
"    mlflow.log_figure(fig_shap_beeswarm, 'shap_beeswarm.png')\n"
"    mlflow.log_figure(fig_shap_bar,      'shap_importance_grouped.png')\n"
"\n"
"    # Figures locales\n"
"    mlflow.log_figure(fig_wf_non_def, 'shap_waterfall_non_defaillant.png')\n"
"    mlflow.log_figure(fig_wf_def,     'shap_waterfall_defaillant.png')\n"
"\n"
"    # Top 20 features en JSON — comparable entre plusieurs runs\n"
"    _top20_dict = (\n"
"        shap_importance.head(20)\n"
"        .set_index('feature')['mean_abs_shap']\n"
"        .round(6)\n"
"        .to_dict()\n"
"    )\n"
"    mlflow.log_dict(_top20_dict, 'shap_top20_features.json')\n"
"\n"
"    # Sauvegarde dans reports/figures/ pour la presentation\n"
"    fig_shap_beeswarm.savefig(\n"
"        FIGURES_DIR / 'shap_beeswarm.png', dpi=150, bbox_inches='tight'\n"
"    )\n"
"    fig_shap_bar.savefig(\n"
"        FIGURES_DIR / 'shap_importance.png', dpi=150, bbox_inches='tight'\n"
"    )\n"
"    fig_wf_non_def.savefig(\n"
"        FIGURES_DIR / 'shap_waterfall_non_defaillant.png', dpi=150, bbox_inches='tight'\n"
"    )\n"
"    fig_wf_def.savefig(\n"
"        FIGURES_DIR / 'shap_waterfall_defaillant.png', dpi=150, bbox_inches='tight'\n"
"    )\n"
"    plt.close('all')\n"
"\n"
"    print('Run MLflow : LightGBM_SHAP enregistre.')\n"
"    print('Artefacts  : beeswarm | importance | 2 waterfall plots | top20 JSON')\n"
"    print(f'Figures sauvegardees dans {FIGURES_DIR}')\n"
))

# Assemblage
nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {"name": "python", "version": "3.11.0"}
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

with open(_ROOT / "notebooks" / "modeling_mlflow.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"Cree : notebooks/modeling_mlflow.ipynb  ({len(cells)} cellules)")
